# Generated by Django 3.1.14 on 2022-05-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fichaVisita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=255)),
                ('localidade', models.CharField(max_length=255)),
                ('quarteirao', models.CharField(max_length=255)),
                ('distrito', models.CharField(max_length=255)),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.IntegerField(default=0)),
            ],
        ),
    ]
