# Generated by Django 3.1.14 on 2022-06-08 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistritosAdm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito_saude', models.CharField(choices=[('DAMOS', 'Distrito Administrativos de Mosqueiro'), ('DAOUT', 'Distrito Administrativo de Outeiro'), ('DAICO', 'Distrito Administrativo de Icoaraci'), ('DABEN', 'Distrito Administrativo do Benguí'), ('DAENT', 'Distrito Administrativo do Entroncamento'), ('DASAC', 'Distrito Administrativo da Sacramenta'), ('DABEL', 'Distrito Administrativo de Belém'), ('DAGUA', 'Distrito Administrativo de Guamá')], default='DAMOS', max_length=5, verbose_name='DA')),
                ('bairro', models.IntegerField(choices=[(1, 'Cidade Velha'), (2, 'Campina'), (3, 'Reduto'), (4, 'Umarizal'), (5, 'Telegrafo'), (6, 'Sacramenta'), (7, 'Pedreira'), (8, 'Marco'), (9, 'Souza'), (10, 'Marambaia'), (11, 'Canudos'), (12, 'Fatima'), (13, 'Sao Bras'), (14, 'Nazare'), (15, 'Batista Campos'), (16, 'Jurunas'), (17, 'Condor'), (18, 'Guama'), (19, 'Terra Firme'), (20, 'Cremacao'), (21, 'Val De Cans'), (22, 'Miramar'), (23, 'Pratinha'), (24, 'Tapana'), (25, 'Bengui'), (26, 'Maracangalha'), (27, 'Barreiro'), (28, 'Universitario'), (29, 'Curio Utinga'), (30, 'Aura'), (31, 'Castanheira'), (32, 'Aguas Lindas'), (33, 'Guanabara'), (34, 'Sao Clemente'), (35, 'Parque Guajara'), (36, 'Tenone'), (37, 'Aguas Negras'), (38, 'Maracacuera'), (39, 'Parque Verde'), (40, 'Cruzeiro'), (41, 'Ponta Grossa'), (42, 'Mangueirao'), (43, 'Cabanagem'), (44, 'Campina De Icoaraci'), (45, 'Paracuri'), (46, 'Agulha'), (47, 'Una'), (48, 'Coqueiro'), (49, 'Sao Jao De Outeiro'), (50, 'Itaiteua'), (51, 'Aguas Negra'), (52, 'Maracaja'), (53, 'Vila'), (54, 'Praia Grande'), (55, 'Farol'), (56, 'Mangueiras'), (57, 'Sao Francisco'), (58, 'Carananduba'), (59, 'Marahu'), (60, 'Paraiso'), (61, 'Baia Do Sol'), (62, 'Sucurijuquara'), (63, 'Caruara'), (64, 'Bonfim'), (65, 'Ariramba'), (66, 'Murubira'), (67, 'Porto Arthur'), (68, 'Natal Do Morumbira'), (69, 'Chapeu Virado'), (70, 'Aeroporto')])),
                ('municipio', models.CharField(default='Belém', max_length=255, verbose_name='Município')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255)),
                ('complemento', models.CharField(max_length=255)),
                ('numero', models.PositiveIntegerField(default=0, verbose_name='Número')),
                ('unidade_federacao', models.CharField(default='PA', max_length=2, verbose_name='UF')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_agente', models.CharField(max_length=255, verbose_name='Nome do Agente')),
                ('cargo', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=255, verbose_name='Responsável')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('atividade', models.CharField(max_length=255)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='FichaVisita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=255)),
                ('quarto', models.PositiveIntegerField(default=0)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.distritosadm')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.endereco', verbose_name='Endereço')),
                ('infos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.info', verbose_name='Informações')),
            ],
        ),
    ]
