# Generated by Django 3.1.14 on 2022-06-30 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220630_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichavisita',
            name='infos',
        ),
        migrations.AddField(
            model_name='info',
            name='ficha',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.fichavisita'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
